### ISSUE TITLE
SMD hooks and/or mounting holes for lanyard / case

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/mch2022-badge-hardware#12]
Currently the MCH2021 prototype 2 PCB design does not have mounting holes and mounting hooks for the lanyard.

Bas thinks the SMD lanyard hooks used on the CZ19 badge might be usefull. Some other people asked for holes to attach a 3d printed case to.

**Comment by sebastius** [comment]
If you're doing holes anyway: holes are cheaper 😊 But i really liked the SMD loops the Campzone 19 badge had. Mounting holes are essential for after-camp usage too (and for lasercut/3d printed cases)

**Comment by renzenicolai** [comment]
Holes it is :smile:
