### ISSUE TITLE
Potential overcurrent in the I2S data lines

### ISSUE THREAD

**Issue by xesxen** [badgeteam/mch2022-badge-hardware#19]
When both the ESP32 and the FPGA is driving the I2S interface due to user error (or other reasons) there could be currents up to 35mA (3.3V@94Ohm). The iCE40 UP family specifies an max current of 8mA on 3V3 (Section `sysI/O Single-Ended DC Electrical Characteristics`), and some quick searching yield 12mA for the ESP32.

Maybe we should increase the resistor values from 47ohm to something a bit higher?

**Comment by smunaut** [comment]
JFYI The UP5k drivers have roughly 50 ohm driver impedance.

https://github.com/YosysHQ/icestorm/wiki/UP5k-Driver-Characteristics

**Comment by renzenicolai** [comment]
Changed the resistor values to 220 ohm, 7.5mA @ 3.3v
