### ISSUE TITLE
RTC backup LDO

### ISSUE THREAD

**Issue by tachiniererin** [badgeteam/mch2022-badge-hardware#20]
The AMS1117, U15 in the schematic won't be stable. It has a minimum load current requirement of 5mA typical, and worst case 10mA. In addition, it has a quiescent current of 5-11mA, which will drain the battery really fast.

In addition to that, the output capacitor is only 100nF, which is not enough to make it stable. In the datasheet it's specified with a 22µF tantalum (high ESR) capacitor, a ceramic capacitor has a magnitude less ESR in comparison.

![image](https://user-images.githubusercontent.com/49161598/101294520-0d649c00-3818-11eb-900b-d923dd7ab746.png)

**Comment by sebastius** [comment]
Hmm yeah i agree on that the AMS1117 should be dropped for something better. Any suggestions?

**Comment by tachiniererin** [comment]
Any requirements, e.g. does it have to be available from LCSC? I'll have a look in the morning.

**Comment by sebastius** [comment]
We have a 'local agent' in China doing our purchasing so if LCSC doesnt have it, it might still be available. Our main goal is both cheap and efficient. Cheap in bulk (4000 badges are planned). LCSC would help/make things easier also for the prototype phase. It would mean that the LDO is readily available.

**Comment by tachiniererin** [comment]
Depending on just how cost sensitive you are I would go either with TLV70433 (LCSC part number C94917) or as a cheaper alternative TLV74333 (LCSC part number C408972).

Both are stable with small MLCCs, so what they cost more you save in not needing an electrolytic (or worse, tantalum) capacitor.

**Comment by sebastius** [comment]
it's all community money so the cheaper the better. I prefer not using tantalums, those are a fire hazard and contain a lot of slave labour.

**Comment by tachiniererin** [comment]
A really low-cost alternative would be to supply the RTC through one or two silicon diodes to drop the battery voltage a bit. For example one or two 1N4148W in series, biased with a 200k resistor. Under no circumstances should Vbat then see more than 3.2V.
This then would have a static current consumption of 20µA including the RTC itself, which is even lower than the quiescent current of the cheaper LDO.

This solution would need to be tested though, because the characteristics of the diodes can vary a bit depending on the supplier. It might also be okay to reduce the bias current, if that's an optimization goal.

In total this would probably reduce the costs for this section to less than 1c per badge.

**Comment by tachiniererin** [comment]
Adding a 3.3-V Zener would cancel out the temperature sensitivity of the previous solution:
![image](https://user-images.githubusercontent.com/49161598/101338531-64e92300-387d-11eb-869b-041f678bbfcd.png)

This should be cheaper and better than any LDO for this particular job.

**Comment by renzenicolai** [comment]
Added circuit with 3.3v zener instead of LDO
