### ISSUE TITLE
Bad choice of pin for clk input on FPGA

### ISSUE THREAD

**Issue by smunaut** [badgeteam/mch2022-badge-hardware#22]
If you use pin 37 for clock input, you can't use the PLL of the FPGA.

There are some quirky rules on how this works, but the basic idea is that if the PLL is used then pin 37 can only be an output (you can't use it as input). And pin 35 can either be an output OR the input to the PLL (and input to the PLL only, you can't wire it as an input anywhere else).

My advice:
 * 35: CLK
 * 36: LCD_D6
 * 37: LCD_D7

That means LCD_D7 can only be an output but ... doesn't matter you have the `RD` signal wired to a constant on the LCD anyway so you can't read from it anyway.

**Comment by renzenicolai** [comment]
Changed, thank you.
