### ISSUE TITLE
FPGA: Pull up on CDONE

### ISSUE THREAD

**Issue by smunaut** [badgeteam/mch2022-badge-hardware#27]
Technically the PCA9555PW has weak pull-ups but ... 

The CDONE output is open-drain and it's important to note that if CDONE doesn't rise above Vih because it's not pulled up enough externally, the FPGA *will* *not* startup.

**Comment by renzenicolai** [comment]
The I2C IO expander takes care of this, on prototype 1 the FPGA can be programmed and used as intended.
