### ISSUE TITLE
Flash voltage selection

### ISSUE THREAD

**Issue by tjclement** [badgeteam/mch2022-badge-hardware#29]
I think the pull-up on ESP32's GPIO12 will cause the SPI flash to brown out, because the ESP32 will set it to 1.8v instead of the 3.3v that the WROVER B and E need; only the original WROVER works at 1.8v (and thus with GPIO12 pulled up)

https://www.espressif.com/sites/default/files/documentation/espressif_products_ordering_information_en.pdf
https://www.espressif.com/sites/default/files/documentation/esp32-wrover_datasheet_en.pdf ("strapping pins")
https://www.espressif.com/sites/default/files/documentation/esp32-wrover-b_datasheet_en.pdf
https://www.espressif.com/sites/default/files/documentation/esp32-wrover-e_esp32-wrover-ie_datasheet_en.pdf

**Comment by sebastius** [comment]
Ah, same issue as we had on HackerHotel 2019? If i recall correctly you can burn a fuse to fix this, right?

**Comment by martinling** [comment]
You can - the relevant fuses are `XPD_SDIO_REG`, `SDIO_TIEH` and `sdio_force`, in the "eFuse Controller" chapter in the ESP32 TRM: https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf

But that's an extra step you'd have to do for every single unit, so it would be a lot better to find a way to avoid needing a pullup on that line.

**Comment by renzenicolai** [comment]
Swapped ext i2c with i2s clk/data pins and made IO12 have a pull-down.

I do suggest we burn these fuses and the write-protect fuses on any other unwanted option, that way we can be sure no-one accidentally bricks their badge / stop malicious software.
