### ISSUE TITLE
I2C pullup resistances too high

### ISSUE THREAD

**Issue by martinling** [badgeteam/mch2022-badge-hardware#31]
The pullup resistors on `I2C_SCL` and `I2C_SDA` are currently 10kΩ. My gut feeling is this that this is too high - but let me justify that quantitatively rather than asking you to trust my judgement:

The rise time of I2C signals results from the combination of the pullup resistance and the bus capacitance; so the pullup resistance must be low enough to meet timing requirements, given the worst-case value for the bus capacitance.

There are 5 devices on the bus:

ESP32 (2pF I/O pin capacitance)
STM32F103 (5pF I/O pin capacitance)
PCA9555 (max 10pF I/O pin capacitance)
BNO055 (unspecified - assume max 10pF)
BME680 (unspecified - assume max 10pF)

That gives a total of 37pF on each line, before even considering other sources e.g. parasitic capacitance of the PCB traces.

There's also a Qwiic connector for adding external I2C devices, which would add further capacitance (both from the devices themselves, and the parasitics of the connectors and cables used to connect them). So the worst-case capacitance could get quite high.

The I2C specification is here: https://www.nxp.com/docs/en/user-guide/UM10204.pdf

At 400kHz, the maximum permitted rise time (`t_r`) is 300ns (Table 10). The equation for maximum pullup resistance is given in section 7.1 as: `R_p_max = t_r / (0.8473 * C_b)` where `C_b` is the bus capacitance.

Taking just the known 37pF capacitances above - which already excludes any parasitics - gives us a maximum pullup resistance of `300e-9 / (0.8473 * 37e-12)` = 9569 Ω. So the value of 10kΩ is definitely too high.

Reducing the pullups to 4.7kΩ would allow for up to 75pF bus capacitance, which would provide some overhead.

Personally I would go lower still - if the timings are only barely met then any interference coupled onto the bus, particularly with external wiring, can more easily cause problems.

**Comment by zoe1337** [comment]
Good point, I personally would go for 2.2-kOhm.

**Comment by renzenicolai** [comment]
Changed to 4k7 for now, we can always experiment after receiving the prototype as replacing these resistors is easy.
