### ISSUE TITLE
Comments on the board routing

### ISSUE THREAD

**Issue by smunaut** [badgeteam/mch2022-badge-hardware#35]
While reviewing and fixing some of the schematics, I had a glance at the current layout (obviously not finished ..) around the FPGA and I had a few comments :

* The 100n decoupling caps need to be near the pins they protect (one per pin), not across the chip. `0603` is definitely a bit big, if moving to `0402` would make that easier. But then again, this is also already a dual load board so putting the decoupling on the other side of the chip would make things pretty trivial.

* Also, power pins and associate decoupling should have their own non-shared vias, with large trace to those via (pretty much the width of the pad/via).

* Length matching: This is not required. None of the signals on this board go anywhere fast enough to warrant it. If anything it actually hurt things. For instance the traces to the PMOD would be better served by being routed as pairs, short and close together than the random serpentine that's currently there.

**Comment by renzenicolai** [comment]
Fixed.
