### ISSUE TITLE
Just a concern: I2C pullups

### ISSUE THREAD

**Issue by Wilenzo** [badgeteam/mch2022-badge-hardware#39]
I don't know if FM(+) or HS is being used for I2C, but even when it's not, with a fair amount of I2C devices on the bus you should calculate the pull-up resistors: https://www.ti.com/lit/an/slva689/slva689.pdf?ts=1607836778518

**Comment by martinling** [comment]
I did some calculations on this - see #31.

**Comment by renzenicolai** [comment]
Good point, closing as duplicate of #31
